---
title: "Introduction to lulccR"
author: "Simon Moulds"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to lulccR}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r, echo=FALSE}
knitr::opts_chunk$set(collapse=TRUE, comment="#>")
```

# Introduction
TEXT

# Example application

TEXT

```{r}
library(lulccR)
obs <- ObservedMaps(x=pie,
                    pattern="lu",
                    categories=c(1,2,3),
                    labels=c("forest","built","other"),
                    t=c(0,6,14))
```
TEXT

```{r}
pred <- predictorMaps(x=pie, pattern="pred")
pred <- Predictors(maps=pred)
```
TEXT

```{r}
part <- partition(x=obs@maps[[1]], size=0.5, spatial=FALSE)
# convert initial land use map to RasterBrick where each layer is a boolean
# map for the respective land use category
lu.br <- layerize(obs@maps[[1]])
names(lu.br) <- obs@labels

# extract training and testing partition cells
lu.train.df <- extract(x=lu.br, y=part$train, data.frame=TRUE)
pred.train.df <- as.data.frame(x=pred, cells=part$train)
train.data <- cbind(lu.df, pred.df)

lu.test.df <- extract(x=lu.br, y=part$test, data.frame=TRUE)
pred.test.df <- as.data.frame(x=pred, cells=part$test)
test.data <- cbind(lu.test.df, pred.test.df)
```
TEXT

```{r}
# fit glm models
forest.form <- formula(forest ~ 1)
forest.glm <- glm(forest.form, family=binomial, data=train.data) 
built.form <- formula(built ~ pred_001 + pred_002 + pred_003)
built.glm <- glm(built.form, family=binomial, data=train.data)
other.form <- formula(other ~ pred_001 + pred_002)
other.glm <- glm(other.form, family=binomial, data=train.data)

# create StatModels object
mods <- StatModels(models=list(forest.glm, built.glm, other.glm), obs=obs)
```
TEXT

```{r}
# assess model fit with generic ROCR functions
glm.pred <- predictionMulti(models=mods,
                            obs=obs,
                            pred=pred,
                            partition=part$test)

glm.perf <- performanceMulti(prediction=glm.pred, measure="rch")

# plot ROC curve
plot.roc(list(glm=glm.perf))
```
TEXT

```{r}
# obtain demand scenario
dmd <- approxExtrapDemand(obs=obs, tout=0:14)
```

```{r}
# prepare model input
input <- ModelInput(x=obs,
                    pred=pred,
                    models=mods,
                    time=0:14,
                    demand=dmd)

clues.rules <- matrix(data=c(1,1,1,
                             1,1,1,
                             1,1,1), nrow=3, ncol=3, byrow=TRUE)

clues.parms <- list(jitter.f=0.0002,
                    scale.f=0.000001,
                    max.iter=1000,
                    max.diff=50,
                    ave.diff=50)

clues.input <- CluesModelInput(x=input,
                               elas=c(0.2,0.2,0.2),
                               rules=clues.rules,
                               parms=clues.parms)

ordered.input <- OrderedModelInput(x=input)
```
TEXT

```{r}
# allocate land use change using two methods
clues.maps <- allocate(clues.input)
ordered.maps <- allocate(ordered.input)
```
TEXT

```{r}
# evaluate CLUE-S model output
clues.tabs <- ThreeMapComparison(rt1=obs@maps[[1]],
                                 rt2=obs@maps[[2]],
                                 st2=clues.maps[[15]],
                                 categories=obs@categories,
                                 labels=obs@labels,
                                 factors=2^(1:10))

# calculate agreement budget and plot
clues.agr <- AgreementBudget(x=clues.tabs)
plot.agreement(clues.agr)

# calculate Figure of Merit and plot
clues.fom <- FigureOfMerit(x=clues.tabs)
plot.fom(clues.fom)
```

# Conclusion
TEXT

# Acknowledgements
TEXT

# References